## YAML Template.
---
version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: teamD
      POSTGRES_PASSWORD: Notas123!
      POSTGRES_DB: NotasApp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: